#!/bin/bash
rm -rf scraped-data/2023-01-1*
rm -rf scraped-data/2023-02-1*
rm -rf scraped-data/2023-03-1*
rm -rf scraped-data/2023-04-1*
rm -rf scraped-data/2023-05-1*
rm -rf scraped-data/2023-06-1*
rm -rf scraped-data/2023-07-1*
rm -rf scraped-data/2023-08-1*
rm -rf scraped-data/2023-09-1*
rm -rf scraped-data/2023-10-1*
rm -rf scraped-data/2023-11-1*
rm -rf scraped-data/2023-12-1*
