#!/bin/bash

# Keep 2025 scraped data from the 7th and 20th of each month

mkdir -p scraped-data/scraped-data-2025

mv scraped-data/2025-01-07/ scraped-data/scraped-data-2025
mv scraped-data/2025-02-07/ scraped-data/scraped-data-2025
mv scraped-data/2025-03-07/ scraped-data/scraped-data-2025
mv scraped-data/2025-04-07/ scraped-data/scraped-data-2025
mv scraped-data/2025-06-07/ scraped-data/scraped-data-2025
mv scraped-data/2025-08-07/ scraped-data/scraped-data-2025
mv scraped-data/2025-09-07/ scraped-data/scraped-data-2025
mv scraped-data/2025-11-07/ scraped-data/scraped-data-2025
mv scraped-data/2025-12-07/ scraped-data/scraped-data-2025
mv scraped-data/2025-01-20/ scraped-data/scraped-data-2025
mv scraped-data/2025-03-20/ scraped-data/scraped-data-2025
mv scraped-data/2025-04-20/ scraped-data/scraped-data-2025
mv scraped-data/2025-05-20/ scraped-data/scraped-data-2025
mv scraped-data/2025-06-20/ scraped-data/scraped-data-2025
mv scraped-data/2025-07-20/ scraped-data/scraped-data-2025
mv scraped-data/2025-09-20/ scraped-data/scraped-data-2025
mv scraped-data/2025-10-20/ scraped-data/scraped-data-2025
mv scraped-data/2025-11-20/ scraped-data/scraped-data-2025
mv scraped-data/2025-12-20/ scraped-data/scraped-data-2025

